### ISSUE TITLE
[Bug] Malformed line in DESCRIPTION

### ISSUE THREAD

**Issue by nanakiksc** [oriolarques/GEGVIC#2]
In DESCRIPTION, line 8 is malformed as it is a continuation of a multiline paragraph. Lines 7 and 8 are:
```
Description: A workflow to analyse Gene Expression, Genetic Variations and Immune 
cell Composition of tumour samples using Next Generation Sequencing data.
```
Either they should be in a single line:
```
Description: A workflow to analyse Gene Expression, Genetic Variations and Immune cell Composition of tumour samples using Next Generation Sequencing data.
```
or an indent should be added before the second line to make it a continuation of the `Description` field:
```
Description: A workflow to analyse Gene Expression, Genetic Variations and Immune 
    cell Composition of tumour samples using Next Generation Sequencing data.
```
Source:
https://r-pkgs.org/description.html

**Comment by oriolarques** [comment]
Thank you for spotting that error. I have fixed it and now you should be able to proceed with the installation correctly.
