### ISSUE TITLE
paired sample

### ISSUE THREAD

**Issue by shaoyoucheng** [oriolarques/GEGVIC#3]
it does not work for paired sample?

**Comment by oriolarques** [comment]
In the gene expression module there is the option to take that into account by playing with the design formula in the `ge_diff_exp()` function as suggested in the DESeq2 [manual page](http://master.bioconductor.org/packages/release/bioc/vignettes/DESeq2/inst/doc/DESeq2.html#can-i-use-deseq2-to-analyze-paired-samples). However, at the moment there is no direct way to do it in the other modules of the package.
