### ISSUE TITLE
"Wrong in paired sample analysis"

### ISSUE THREAD

**Issue by shaoyoucheng** [oriolarques/GEGVIC#4]
#############Modified function: ge_diff_exp_modification()
function (counts, genes_id, metadata, ref_level, shrink = NULL) 
{
    counts <- preprocess_ge_counts(counts = counts, genes_id = genes_id)
    metadata <- preprocess_ge_meta(metadata = metadata, counts = counts)
    
	
	
	metadata <- data.frame(sample <- metadata$sample, ID <- metadata$ID)
	
	colnames(metadata) <- c("sample", "ID")
	
	dds <- DESeq2::DESeqDataSetFromMatrix(countData = counts, 
        colData = metadata, design = ~ID + sample)
    
	
	dds[[ref_level[1]]] <- stats::relevel(x = dds[[ref_level[1]]], 
        ref = ref_level[2])
    
	
	dds <- DESeq2::DESeq(dds)
    
	
	results_dds <- list()
    if (shrink != "none") {
        
		for (i in seq(from = 2, to = length(resultsNames(dds)))) {
            results_dds[[i - 1]] <- DESeq2::lfcShrink(dds = dds, 
                coef = resultsNames(dds)[i], type = "apeglm")
            names(results_dds)[i - 1] <- DESeq2::resultsNames(dds)[i]
        }
    }
    else {
        for (i in seq(from = 2, to = length(resultsNames(dds)))) {
            results_dds[[i - 1]] <- DESeq2::results(object = dds, 
                name = resultsNames(dds)[i])
            names(results_dds)[i - 1] <- DESeq2::resultsNames(dds)[i]
        }
    }
    return(results_dds)
}

############# incorrect results
> results.dds <- ge_diff_exp_modification(counts = exprSet_pair_exprset,
+                            genes_id = 'ensembl_gene_id',
+                            metadata = phe_paired_clean,
+                            ref_level = c('sample', 'Nontumor'),
+                            shrink = 'apeglm')
estimating size factors
estimating dispersions
gene-wise dispersion estimates
mean-dispersion relationship
final dispersion estimates
fitting model and testing
3 rows did not converge in beta, labelled in mcols(object)$betaConv. Use larger maxit argument with nbinomWaldTest
using 'apeglm' for LFC shrinkage. If used in published research, please cite:
    Zhu, A., Ibrahim, J.G., Love, M.I. (2018) Heavy-tailed prior distributions for
    sequence count data: removing the noise and preserving large differences.
    Bioinformatics. https://doi.org/10.1093/bioinformatics/bty895
using 'apeglm' for LFC shrinkage. If used in published research, please cite:
    Zhu, A., Ibrahim, J.G., Love, M.I. (2018) Heavy-tailed prior distributions for
    sequence count data: removing the noise and preserving large differences.
    Bioinformatics. https://doi.org/10.1093/bioinformatics/bty895

**Comment by oriolarques** [comment]
Regarding this error, the author of the DESeq package suggests the [following](https://support.bioconductor.org/p/p132819/):

*Examine the counts for the rows that are not converging, and consider ways to filter those out. Often these have problematic distribution of counts for the NB, e.g. they contain outliers. If you think they are ignorable (do not represent DE genes) you could just set their p-values and adj p-values to NA.*

**Comment by shaoyoucheng** [comment]
Thanks for your response,but I still have something that need your confirmation. Multiple Group Comparison  and paired sample Comparison should be recommended in "[GEGVIC](https://github.com/oriolarques/GEGVIC)" pipeline.

**Comment by oriolarques** [comment]
I am not sure I understand your point, do you mean that these comparisons should be specifically explained in the manual?

**Comment by shaoyoucheng** [comment]
Multiple Group Comparison means, a variable poses multiple levels. In [GEGVIC](https://github.com/oriolarques/GEGVIC) pipeline, Two groups of comparisons methods are common. Give me an example to illustrate my request，If I want to perform the differential expression analysis between immune_high, immune_middle and immnue_low groups.

**Comment by oriolarques** [comment]
If you have multiple groups you just need to properly set up the metadata object and  GEGVIC will perform multiple group comparisons. In the gene expression module a reference group need to be set and all comparisons versus that group will be performed. This include all the plots and, as stated in the manual page (section 1.2. Differential gene expression) for the table outputs:  
**In the case there are multiple levels of comparison the object will be in a form of a list**. Regarding the other two modules, you need to make sure you choose the appropriate amount of colors and also to set the `compare` parameters to either ‘anova’ or ‘kruskal.test’.
I agree with you that the manual page could include an example with multiple comparisons but we chose a minimal example with biological meaning (MSI vs MSS colorectal cancer patients) that can be reproduced without any problems regarding computational power of the user.
