### ISSUE TITLE
Error “cibersort”

### ISSUE THREAD

**Issue by shaoyoucheng** [oriolarques/GEGVIC#5]
>>> Running cibersort
Error in rlang::call2(CIBERSORT, !!!arguments) : 
  object 'CIBERSORT' not found

**Comment by oriolarques** [comment]
As indicated in the README:
**To use the CIBERSORT, the user need to register on the CIBERSORT web page (https://cibersort.stanford.edu/), obtain a license and download the source code in form of two files CIBERSORT.R and LM22.txt. Then, the user need to specify the path to the storage location of such files in the cibersort argument.**

**Comment by shaoyoucheng** [comment]
Error again when set as following
set_cibersort_binary("/cibersort/CIBERSORT.R")
set_cibersort_binary("/cibersort/LM22.txt")

**Comment by oriolarques** [comment]
You need to make sure that the path is correct. The path you showed should work if the cibersort folder is located in the current working directory. If that is not the case you should indicate the full path to locate the files.

**Comment by shaoyoucheng** [comment]
Thanks for your help
